name: Regenerate Paws Website

on:
  schedule:
    # At 12:00, on day 10 of the month, every 4 months
    # Giving 10 days for paws regen to be approved
    - cron: "0 12 10 */4 *"
  workflow_dispatch:
    inputs:
    text_to_print:
      description: "Manual re-build"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: regen-site

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Get requirements
        run: make requirements

      - name: Create Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -c regen_paws_website

      - name: Update Paws Submodule
        run: |
          make update-deps

      - name: Get Paws requirements
        run: |
          remotes::install_deps('vendor/paws/paws.common', dependencies = TRUE)
          remotes::install_local('vendor/paws/paws.common', force = TRUE)
        shell: Rscript {0}

      - name: Regen Paws Site
        run: |
          make regen-site

      - name: Create Commit Message
        run: |
          git add .
          git commit -m "Regenerate Paws Website"
          git push origin regen_paws_website

      - name: Create Github Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Regenerate Paws Website" --body "Regenerate Paws Website"
